;
; BIND data file for local loopback interface
;
$TTL	5
@	IN	SOA	ns.ali-algburi.sb.uclllabs.be. admin.ali-algburi.sb.uclllabs.be. (
                   2147484325         ; Serial 
			      5		; Refresh
			      5		; Retry
			      5		; Expire
			      5 )	; Negative Cache TTL
;
@	IN	NS	ns.ali-algburi.sb.uclllabs.be.
@	IN	NS	ns1.uclllabs.be.
@	IN	NS	ns2.uclllabs.be.
@	IN	A	193.191.177.129
@	IN	AAAA	2001:6a8:2880:a077::81
@	IN	NS	ns.sandeep-singh.sb.uclllabs.be.

ns	IN	AAAA	2001:6a8:2880:a077::81
ns	IN	A	193.191.177.129
www	IN	A	193.191.177.129
www1	IN	A	193.191.177.129
www2	IN	A	193.191.177.129
test	IN	A	193.191.177.254
secure	IN	A	193.191.177.129
supersecure	IN	A	193.191.177.129
_acme-challenge.secure.ali-algburi.sb.uclllabs.be.	IN	TXT	"LAleeMBIlWoX-0o9G_lokbKIfLKAYPvFUUiA6bQdWig"
_acme-challenge.supersecure.ali-algburi.sb.uclllabs.be. IN	TXT	"4Jk0K2y28b2fn6p_q4zxVwW3C4YjvxSrqclt5U1mlxs"
_acme-challenge.mx.ali-algburi.sb.uclllabs.be.	IN	TXT	"nqWQ6eQt51n-X1MEnvSG_Uo7rMaVkf1skkNvEW6l81E"

us.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
us.ali-algburi.sb.uclllabs.be.	IN	NS	ns.ali-algburi.sb.uclllabs.be.

ali-algburi.sb.uclllabs.be.	IN	MX	10	mx.ali-algburi.sb.uclllabs.be.
mx.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129	
mx.ali-algburi.sb.uclllabs.be.	IN	AAAA	2001:6a8:2880:a077::81

lemme.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
lemme.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneni1equ.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneni1equ.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiz1phi.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiz1phi.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeeto2a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeeto2a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneyahxe2.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneyahxe2.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoopi3l.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoopi3l.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexoh1ya.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexoh1ya.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonewazoa1.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonewazoa1.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexee4ie.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexee4ie.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonetuqu9l.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonetuqu9l.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneuo7wi0.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneuo7wi0.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonevej1bo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonevej1bo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepail6i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepail6i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexoeg2n.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexoeg2n.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneyati0a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneyati0a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonechi4ee.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonechi4ee.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehuuwo3.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehuuwo3.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonecheip5.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonecheip5.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehie7qu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehie7qu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonereez4a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonereez4a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneai2she.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneai2she.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonere6uu5.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonere6uu5.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiep1ei.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiep1ei.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahh4in.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahh4in.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonequi6ia.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonequi6ia.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonegij6yo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonegij6yo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoor1ua.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoor1ua.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebuuh4e.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebuuh4e.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneshei1h.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneshei1h.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahs8oo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahs8oo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepief8u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepief8u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefah2em.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefah2em.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonegaes4o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonegaes4o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonedaif7o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonedaif7o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonesah8ih.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonesah8ih.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonedaelu8.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonedaelu8.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaey7ei.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaey7ei.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeew0ro.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeew0ro.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeeje8e.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeeje8e.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahlei6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahlei6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneew7eew.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneew7eew.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneda4lu7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneda4lu7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneieho3g.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneieho3g.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehoh9xu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehoh9xu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoshai1.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoshai1.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneegae7u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneegae7u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefae8we.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefae8we.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneangoh6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneangoh6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneefiy3w.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneefiy3w.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehee2fo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehee2fo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeigh9f.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeigh9f.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneshane4.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneshane4.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonevoxu4p.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonevoxu4p.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeev3ge.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeev3ge.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneshoo5a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneshoo5a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeeg1ca.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeeg1ca.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonequauv3.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonequauv3.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneohbez2.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneohbez2.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaeke3i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaeke3i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepha3so.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepha3so.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneak1pah.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneak1pah.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneyoh6ei.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneyoh6ei.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeegho3.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeegho3.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiy6pho.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiy6pho.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahhai0.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahhai0.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonemoh4ji.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonemoh4ji.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeewee8.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeewee8.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiez1ee.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiez1ee.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeec0ee.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeec0ee.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneieh4zo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneieh4zo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonechahf0.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonechahf0.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefie7ne.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefie7ne.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonekaiv5i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonekaiv5i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaing8a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaing8a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonezahr0a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonezahr0a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepae2oh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepae2oh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
