;
; BIND data file for local loopback interface
;
$TTL	5
@	IN	SOA	ns.ali-algburi.sb.uclllabs.be. admin.ali-algburi.sb.uclllabs.be. (
                   2147483736         ; Serial 
			      5		; Refresh
			      5		; Retry
			      5		; Expire
			      5 )	; Negative Cache TTL
;
@	IN	NS	ns.ali-algburi.sb.uclllabs.be.
@	IN	NS	ns1.uclllabs.be.
@	IN	NS	ns2.uclllabs.be.
@	IN	A	193.191.177.129
@	IN	NS	ns.sandeep-singh.sb.uclllabs.be.

ns	IN	A	193.191.177.129
www	IN	A	193.191.177.129
www1	IN	A	193.191.177.129
www2	IN	A	193.191.177.129
test	IN	A	193.191.177.254
secure	IN	A	193.191.177.129
supersecure	IN	A	193.191.177.129
_acme-challenge.secure.ali-algburi.sb.uclllabs.be.	IN	TXT	"LAleeMBIlWoX-0o9G_lokbKIfLKAYPvFUUiA6bQdWig"
_acme-challenge.supersecure.ali-algburi.sb.uclllabs.be. IN	TXT	"4Jk0K2y28b2fn6p_q4zxVwW3C4YjvxSrqclt5U1mlxs"
_acme-challenge.mx.ali-algburi.sb.uclllabs.be.	IN	TXT	"nqWQ6eQt51n-X1MEnvSG_Uo7rMaVkf1skkNvEW6l81E"

us.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
us.ali-algburi.sb.uclllabs.be.	IN	NS	ns.ali-algburi.sb.uclllabs.be.

ali-algburi.sb.uclllabs.be.	IN	MX	10	mx.ali-algburi.sb.uclllabs.be.
mx.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129	

lemme.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
lemme.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaing6i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaing6i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeem7va.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeem7va.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneifup6a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneifup6a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonezei6ae.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonezei6ae.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefe3iej.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefe3iej.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonecixeu2.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonecixeu2.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonechous7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonechous7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneii4ohh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneii4ohh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneuxee3f.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneuxee3f.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneidie3z.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneidie3z.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebae0th.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebae0th.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaghoh6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaghoh6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneao1lah.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneao1lah.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneuzah1m.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneuzah1m.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebae6ee.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebae6ee.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonenut0un.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonenut0un.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneelia0z.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneelia0z.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonezee7ch.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonezee7ch.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaisij6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaisij6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonequoo9j.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonequoo9j.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexai3ze.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexai3ze.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoum2ph.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoum2ph.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahw4ph.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahw4ph.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeinoh7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeinoh7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneceew6o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneceew6o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeu5iph.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeu5iph.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneumibu7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneumibu7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonedau3aa.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonedau3aa.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonecahsh7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonecahsh7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaeyah4.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaeyah4.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneanahp3.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneanahp3.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneob2sah.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneob2sah.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeeg5ah.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeeg5ah.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneio6ev8.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneio6ev8.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoosah1.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoosah1.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonegah4oh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonegah4oh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaisho0.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaisho0.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefe2eig.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefe2eig.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeic2ux.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeic2ux.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonekoo9ch.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonekoo9ch.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonerab7qu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonerab7qu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepah6ju.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepah6ju.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaixa4m.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaixa4m.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneach8fa.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneach8fa.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneietoo0.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneietoo0.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoc4aer.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoc4aer.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiloh8c.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiloh8c.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneul1oow.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneul1oow.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahb0ie.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahb0ie.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonewoph7k.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonewoph7k.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahvie1.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahvie1.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneteil9u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneteil9u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneein7ne.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneein7ne.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneyu3iey.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneyu3iey.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneohj2be.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneohj2be.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonezoegh8.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonezoegh8.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeechu7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeechu7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonesahj5u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonesahj5u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehuak4i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehuak4i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneboof5a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneboof5a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoop9as.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoop9as.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebo6ahs.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebo6ahs.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonegoh7lo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonegoh7lo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonees0wiu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonees0wiu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneroif0u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneroif0u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepoo3fo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepoo3fo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonegieph0.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonegieph0.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexeik5u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexeik5u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneies2nu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneies2nu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneifohj9.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneifohj9.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeet3ph.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeet3ph.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeefee1.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeefee1.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaech1n.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaech1n.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneesit1i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneesit1i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonetai4ei.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonetai4ei.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonejaec9j.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonejaec9j.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonesee6ah.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonesee6ah.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiel5ep.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiel5ep.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeex7la.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeex7la.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
