;
; BIND data file for local loopback interface
;
$TTL	5
@	IN	SOA	ns.ali-algburi.sb.uclllabs.be. admin.ali-algburi.sb.uclllabs.be. (
                   2147484240         ; Serial 
			      5		; Refresh
			      5		; Retry
			      5		; Expire
			      5 )	; Negative Cache TTL
;
@	IN	NS	ns.ali-algburi.sb.uclllabs.be.
@	IN	NS	ns1.uclllabs.be.
@	IN	NS	ns2.uclllabs.be.
@	IN	A	193.191.177.129
@	IN	AAAA	2001:6a8:2880:a077::81
@	IN	NS	ns.sandeep-singh.sb.uclllabs.be.

ns	IN	AAAA	2001:6a8:2880:a077::81
ns	IN	A	193.191.177.129
www	IN	A	193.191.177.129
www1	IN	A	193.191.177.129
www2	IN	A	193.191.177.129
test	IN	A	193.191.177.254
secure	IN	A	193.191.177.129
supersecure	IN	A	193.191.177.129
_acme-challenge.secure.ali-algburi.sb.uclllabs.be.	IN	TXT	"LAleeMBIlWoX-0o9G_lokbKIfLKAYPvFUUiA6bQdWig"
_acme-challenge.supersecure.ali-algburi.sb.uclllabs.be. IN	TXT	"4Jk0K2y28b2fn6p_q4zxVwW3C4YjvxSrqclt5U1mlxs"
_acme-challenge.mx.ali-algburi.sb.uclllabs.be.	IN	TXT	"nqWQ6eQt51n-X1MEnvSG_Uo7rMaVkf1skkNvEW6l81E"

us.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
us.ali-algburi.sb.uclllabs.be.	IN	NS	ns.ali-algburi.sb.uclllabs.be.

ali-algburi.sb.uclllabs.be.	IN	MX	10	mx.ali-algburi.sb.uclllabs.be.
mx.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129	
mx.ali-algburi.sb.uclllabs.be.	IN	AAAA	2001:6a8:2880:a077::81

lemme.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
lemme.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaing6i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaing6i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeem7va.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeem7va.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneifup6a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneifup6a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonezei6ae.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonezei6ae.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefe3iej.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefe3iej.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonecixeu2.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonecixeu2.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonechous7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonechous7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneii4ohh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneii4ohh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneuxee3f.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneuxee3f.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneidie3z.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneidie3z.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebae0th.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebae0th.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaghoh6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaghoh6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneao1lah.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneao1lah.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneuzah1m.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneuzah1m.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebae6ee.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebae6ee.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonenut0un.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonenut0un.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneelia0z.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneelia0z.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonezee7ch.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonezee7ch.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaisij6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaisij6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonequoo9j.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonequoo9j.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexai3ze.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexai3ze.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoum2ph.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoum2ph.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahw4ph.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahw4ph.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeinoh7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeinoh7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneceew6o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneceew6o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeu5iph.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeu5iph.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneumibu7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneumibu7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonedau3aa.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonedau3aa.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonecahsh7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonecahsh7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaeyah4.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaeyah4.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneanahp3.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneanahp3.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneob2sah.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneob2sah.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeeg5ah.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeeg5ah.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneio6ev8.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneio6ev8.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoosah1.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoosah1.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonegah4oh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonegah4oh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaisho0.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaisho0.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefe2eig.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefe2eig.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeic2ux.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeic2ux.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonekoo9ch.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonekoo9ch.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonerab7qu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonerab7qu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepah6ju.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepah6ju.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaixa4m.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaixa4m.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneach8fa.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneach8fa.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneietoo0.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneietoo0.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoc4aer.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoc4aer.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiloh8c.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiloh8c.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneul1oow.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneul1oow.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahb0ie.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahb0ie.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonewoph7k.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonewoph7k.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahvie1.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahvie1.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneteil9u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneteil9u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneein7ne.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneein7ne.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneyu3iey.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneyu3iey.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneohj2be.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneohj2be.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonezoegh8.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonezoegh8.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeechu7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeechu7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonesahj5u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonesahj5u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehuak4i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehuak4i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneboof5a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneboof5a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoop9as.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoop9as.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebo6ahs.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebo6ahs.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonegoh7lo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonegoh7lo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonees0wiu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonees0wiu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneroif0u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneroif0u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepoo3fo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepoo3fo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonegieph0.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonegieph0.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexeik5u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexeik5u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneies2nu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneies2nu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneifohj9.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneifohj9.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeet3ph.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeet3ph.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeefee1.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeefee1.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaech1n.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaech1n.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneesit1i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneesit1i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonetai4ei.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonetai4ei.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonejaec9j.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonejaec9j.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonesee6ah.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonesee6ah.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiel5ep.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiel5ep.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeex7la.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeex7la.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonevohz8r.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonevohz8r.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaere6f.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaere6f.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneshaex1.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneshaex1.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeaw8ae.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeaw8ae.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaeph5o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaeph5o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneowi0ai.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneowi0ai.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonetoob4a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonetoob4a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefu8az7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefu8az7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoo5fed.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoo5fed.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonekae1co.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonekae1co.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebohma6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebohma6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneyua1oe.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneyua1oe.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeech8f.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeech8f.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneue3oyi.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneue3oyi.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneishec5.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneishec5.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneai2ohm.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneai2ohm.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneowe8ra.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneowe8ra.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonekoh9ej.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonekoh9ej.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoosh1i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoosh1i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneief2ei.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneief2ei.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonealae7c.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonealae7c.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonequo1ee.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonequo1ee.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonegu6wu5.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonegu6wu5.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeeth5p.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeeth5p.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonewain0l.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonewain0l.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeeng6o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeeng6o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoos6if.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoos6if.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneehah1f.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneehah1f.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexoh6th.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexoh6th.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonerae2th.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonerae2th.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneae9pah.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneae9pah.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeih1ee.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeih1ee.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneujeh1a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneujeh1a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaqu8ei.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaqu8ei.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneieyou9.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneieyou9.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneied0un.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneied0un.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonemae3ga.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonemae3ga.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonegahn6p.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonegahn6p.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonees2moa.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonees2moa.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepoo5ce.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepoo5ce.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonethohs7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonethohs7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoj5ka7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoj5ka7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehei9oo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehei9oo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahy5ba.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahy5ba.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonedieni8.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonedieni8.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefae4oo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefae4oo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaith1i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaith1i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehohz3u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehohz3u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneohk6ru.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneohk6ru.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneao7tud.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneao7tud.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneap1pho.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneap1pho.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexae0ph.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexae0ph.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneal6oow.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneal6oow.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneain7oh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneain7oh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneef1eim.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneef1eim.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahsh5u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahsh5u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonechoo3w.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonechoo3w.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahl0el.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahl0el.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonelau6om.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonelau6om.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiewe1r.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiewe1r.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonejahbo7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonejahbo7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneuquoo4.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneuquoo4.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneloh2oi.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneloh2oi.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonekomo9o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonekomo9o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaar6pe.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaar6pe.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneohn2mi.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneohn2mi.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneooj8an.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneooj8an.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneauve9o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneauve9o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaecax4.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaecax4.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonedinee3.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonedinee3.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexiez2o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexiez2o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonezeip5a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonezeip5a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneyae5xu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneyae5xu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepiez0o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepiez0o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaeguu4.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaeguu4.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepixi0h.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepixi0h.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexah0oh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexah0oh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneuaqu9d.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneuaqu9d.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehae2sh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehae2sh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonechu8xo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonechu8xo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehahte6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehahte6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonewoco3t.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonewoco3t.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonevavaa5.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonevavaa5.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneook4oh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneook4oh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeefi0u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeefi0u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaeyi6o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaeyi6o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoipus2.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoipus2.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneon6ael.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneon6ael.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneef1ohd.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneef1ohd.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonenuepi9.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonenuepi9.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiequ7a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiequ7a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiezei5.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiezei5.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneii3chi.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneii3chi.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonenahko4.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonenahko4.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahz9pe.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahz9pe.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoow0ai.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoow0ai.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeizee5.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeizee5.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneval3oh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneval3oh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonedee0mi.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonedee0mi.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaich8z.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaich8z.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonesekah4.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonesekah4.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonephoo6e.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonephoo6e.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneuo1aet.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneuo1aet.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeil2si.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeil2si.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneash9ro.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneash9ro.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneleeng1.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneleeng1.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneohvoh4.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneohvoh4.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneies5ja.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneies5ja.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepohn6o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepohn6o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneohl3oi.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneohl3oi.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneduigh0.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneduigh0.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonedai8ti.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonedai8ti.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonewohth8.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonewohth8.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebei8xi.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebei8xi.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneith4sh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneith4sh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaepho5.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaepho5.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepe1ip5.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepe1ip5.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehahj2o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehahj2o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefooce3.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefooce3.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefaig6a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefaig6a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaey8ki.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaey8ki.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneyoog3u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneyoog3u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonekoo3ba.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonekoo3ba.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneshiu9r.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneshiu9r.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonean3ne9.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonean3ne9.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneyu9eox.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneyu9eox.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneyei2gi.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneyei2gi.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonenahle1.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonenahle1.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahn3ei.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahn3ei.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonetheth5.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonetheth5.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeh7woh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeh7woh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonejiub2u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonejiub2u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneyei3mi.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneyei3mi.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoak8ph.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoak8ph.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonele9cah.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonele9cah.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahph2o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahph2o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonetohmi7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonetohmi7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahf6oh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahf6oh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaezae4.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaezae4.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoxah2o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoxah2o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonequie1o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonequie1o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneesee2e.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneesee2e.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneootoh6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneootoh6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoi0uw2.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoi0uw2.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonevoolu8.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonevoolu8.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonesao0mi.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonesao0mi.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonegeith4.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonegeith4.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeojee6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeojee6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonelohz8e.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonelohz8e.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonerah0au.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonerah0au.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonetae6wa.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonetae6wa.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneohz2ju.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneohz2ju.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeibeb3.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeibeb3.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaik7ch.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaik7ch.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonequo2be.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonequo2be.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonerei1ya.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonerei1ya.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonejeu2bo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonejeu2bo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeey1qu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeey1qu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeid9vu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeid9vu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebie9ah.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebie9ah.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonetaix2t.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonetaix2t.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneub1oom.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneub1oom.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonesei9eb.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonesei9eb.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoo2egh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoo2egh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonezatem7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonezatem7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehoo4yu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehoo4yu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeiqu6i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeiqu6i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonezeet1z.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonezeet1z.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehae9co.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehae9co.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonece6eeg.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonece6eeg.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneipaek6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneipaek6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonejee0te.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonejee0te.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeigh7a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeigh7a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeiche8.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeiche8.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneog6hah.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneog6hah.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneug8kah.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneug8kah.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeik8yu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeik8yu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonekuij2t.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonekuij2t.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonede1hu3.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonede1hu3.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonejoox2u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonejoox2u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonechaiv0.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonechaiv0.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeij7oh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeij7oh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiew0fe.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiew0fe.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneail4ko.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneail4ko.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaim3ou.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaim3ou.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneboox0o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneboox0o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahy1th.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahy1th.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaor5ee.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaor5ee.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoovoh7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoovoh7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahg1ko.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahg1ko.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneohy1ki.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneohy1ki.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiepei7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiepei7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonenah0oi.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonenah0oi.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehoo1ee.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehoo1ee.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneana8du.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneana8du.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonekaeph6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonekaeph6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefipah9.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefipah9.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneti3zie.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneti3zie.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexoon3e.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexoon3e.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeb3ahb.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeb3ahb.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehie2ge.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehie2ge.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaesui7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaesui7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonede8ahw.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonede8ahw.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahjoh5.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahjoh5.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneohke9i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneohke9i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaiwei2.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaiwei2.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiey3sh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiey3sh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiech0g.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiech0g.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneish3io.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneish3io.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeelo5e.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeelo5e.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonezei9oo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonezei9oo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneshie6a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneshie6a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexie4pu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexie4pu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneedoet6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneedoet6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonetev7us.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonetev7us.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonetee0ei.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonetee0ei.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeith0u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeith0u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneto0ein.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneto0ein.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoot2oo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoot2oo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexif4ki.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexif4ki.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneohy3iu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneohy3iu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahzeo6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahzeo6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonethei9t.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonethei9t.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonelo0ael.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonelo0ael.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonetiy6za.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonetiy6za.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeg1che.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeg1che.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepeep2f.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepeep2f.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefee0ei.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefee0ei.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneco6eu2.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneco6eu2.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonewae9ai.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonewae9ai.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneud3ua4.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneud3ua4.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeek6oh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeek6oh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonesidee1.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonesidee1.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaex6sh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaex6sh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaide3s.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaide3s.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneechun9.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneechun9.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneese0ai.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneese0ai.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebei8xa.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebei8xa.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepae9oh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepae9oh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebeix6b.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebeix6b.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneael6ah.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneael6ah.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneca6eij.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneca6eij.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonedoo5ee.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonedoo5ee.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonethoh7x.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonethoh7x.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneohyoo7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneohyoo7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaeng2u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaeng2u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonegay5ri.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonegay5ri.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonedijei0.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonedijei0.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefee5ei.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefee5ei.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonenahs6f.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonenahs6f.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonephena3.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonephena3.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonezuj1ph.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonezuj1ph.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneusiek8.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneusiek8.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneuti5ee.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneuti5ee.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebiet1u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebiet1u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneii2iay.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneii2iay.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaveu6v.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaveu6v.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonewu7ufo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonewu7ufo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebequ9d.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebequ9d.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneteeh4a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneteeh4a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneieth2i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneieth2i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonevie5ia.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonevie5ia.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoov5ce.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoov5ce.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaiph5u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaiph5u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneih1mie.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneih1mie.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonethuu5i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonethuu5i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaa4ho3.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaa4ho3.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexa0eez.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexa0eez.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneetied2.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneetied2.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonenoo2ie.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonenoo2ie.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiu7sai.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiu7sai.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaiqu9u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaiqu9u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneohng1e.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneohng1e.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneevahb4.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneevahb4.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneooph3e.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneooph3e.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebe4woo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebe4woo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneho7ohw.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneho7ohw.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeipo9j.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeipo9j.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoopee8.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoopee8.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeen5ie.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeen5ie.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahfae3.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahfae3.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefoqu7d.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefoqu7d.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneath1ch.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneath1ch.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonekieb3v.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonekieb3v.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonetok5ee.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonetok5ee.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneloos7i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneloos7i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebio6wi.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebio6wi.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonemih2zo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonemih2zo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonevuwoo4.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonevuwoo4.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneju4thu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneju4thu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneun2tha.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneun2tha.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneyoom3u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneyoom3u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonevaiz4d.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonevaiz4d.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonecheid4.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonecheid4.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneajeeh1.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneajeeh1.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaic0ae.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaic0ae.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoot5uw.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoot5uw.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonedah5li.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonedah5li.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonevae0li.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonevae0li.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonecaev3e.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonecaev3e.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonethu2oo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonethu2oo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoon2uf.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoon2uf.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneohth8j.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneohth8j.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneuo3qua.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneuo3qua.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonesah0oo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonesah0oo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexei7oh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexei7oh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonetie4ih.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonetie4ih.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneuu7oot.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneuu7oot.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefeego8.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefeego8.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonedeiz1f.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonedeiz1f.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeo1roo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeo1roo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexee4ie.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexee4ie.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonekoox7u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonekoox7u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneohjaz5.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneohjaz5.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonecei5ie.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonecei5ie.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaiqu0j.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaiqu0j.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaewo8y.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaewo8y.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneukei3t.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneukei3t.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonemea1ai.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonemea1ai.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaipu2e.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaipu2e.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneree7eo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneree7eo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonerup2so.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonerup2so.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexi1quu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexi1quu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoonah8.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoonah8.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexooh1a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexooh1a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehaesh2.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehaesh2.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonego0iuc.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonego0iuc.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepaep3h.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepaep3h.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneier3ei.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneier3ei.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonewah2oh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonewah2oh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonegowa5u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonegowa5u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexea4oh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexea4oh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoogah3.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoogah3.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefohy6o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefohy6o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneohsei4.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneohsei4.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehoi0ph.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehoi0ph.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneen5sah.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneen5sah.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonemer5ei.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonemer5ei.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeid1ra.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeid1ra.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiet8ei.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiet8ei.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonede3ix2.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonede3ix2.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneuidah7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneuidah7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneci0eir.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneci0eir.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeet9oo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeet9oo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonevima2o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonevima2o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonetee1ie.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonetee1ie.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeexee8.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeexee8.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepaime6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepaime6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneohh8uh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneohh8uh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonemaish4.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonemaish4.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeas9ik.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeas9ik.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebu3jai.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebu3jai.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeo3cah.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeo3cah.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonedoo0ei.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonedoo0ei.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonesex4go.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonesex4go.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahl2ee.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahl2ee.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneood2ma.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneood2ma.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonejai7mu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonejai7mu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneog4vee.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneog4vee.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneup6bio.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneup6bio.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneroa7iz.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneroa7iz.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonejeek5f.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonejeek5f.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneulai9i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneulai9i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonechai7p.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonechai7p.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonesoow0e.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonesoow0e.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebahn5u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebahn5u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeed7ve.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeed7ve.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaew5ku.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaew5ku.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoaw4ta.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoaw4ta.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneuoghe4.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneuoghe4.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneafeac6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneafeac6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebe0ahs.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebe0ahs.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonequuk0w.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonequuk0w.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonecee4oh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonecee4oh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoongu2.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoongu2.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaol7ui.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaol7ui.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonevahci3.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonevahci3.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonevie6th.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonevie6th.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonequu6uo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonequu6uo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneib3iti.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneib3iti.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahnei3.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahnei3.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneau2fae.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneau2fae.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonebee6ee.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonebee6ee.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneuquae2.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneuquae2.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneit9dee.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneit9dee.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiey2xu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiey2xu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneceez5o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneceez5o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneooghu2.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneooghu2.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonechew1i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonechew1i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahr6yu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahr6yu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonemipah2.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonemipah2.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneok8ohy.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneok8ohy.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonewegh4r.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonewegh4r.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneuay3so.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneuay3so.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeeph6p.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeeph6p.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonephah4u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonephah4u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahng9a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahng9a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaed8ak.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaed8ak.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonetie7pe.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonetie7pe.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneto6aec.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneto6aec.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonein2chu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonein2chu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoof9su.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoof9su.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeim4xu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeim4xu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonezoono8.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonezoono8.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonesie0ai.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonesie0ai.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonechei1a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonechei1a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeirae2.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeirae2.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonexai5eh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonexai5eh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonezee4ik.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonezee4ik.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonecae4oo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonecae4oo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonedohxi6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonedohxi6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonephai8n.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonephai8n.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneho3roo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneho3roo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefohgh0.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefohgh0.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneyie3ow.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneyie3ow.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonephoh1i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonephoh1i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneee7aih.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneee7aih.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaeyah2.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaeyah2.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneuch7bo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneuch7bo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneio2iex.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneio2iex.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeidoo6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeidoo6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneechoo9.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneechoo9.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeol6ai.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeol6ai.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonewaer8a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonewaer8a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeith6o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeith6o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeerip6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeerip6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaefam5.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaefam5.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneechai6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneechai6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneek0hik.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneek0hik.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneuz6eid.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneuz6eid.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneooc9gi.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneooc9gi.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehau1oo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehau1oo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneriez4g.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneriez4g.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeitah1.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeitah1.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoiv6us.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoiv6us.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneepoh5u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneepoh5u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonewaez1i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonewaez1i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneea1aib.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneea1aib.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonekaizo2.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonekaizo2.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiewei1.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiewei1.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneahra4u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneahra4u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonekee5wi.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonekee5wi.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneif6aep.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneif6aep.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneshew0k.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneshew0k.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonephuu5l.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonephuu5l.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeevib8.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeevib8.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneleng5i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneleng5i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiaqu7i.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiaqu7i.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonenae9ai.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonenae9ai.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeinu4d.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeinu4d.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoor1il.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoor1il.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneyue8hu.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneyue8hu.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonesoo4gi.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonesoo4gi.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefoo0ei.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefoo0ei.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeek0io.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeek0io.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeowad5.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeowad5.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneyae0ie.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneyae0ie.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonefae6eo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonefae6eo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneyah5ai.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneyah5ai.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepam7oh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepam7oh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonemaaci7.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonemaaci7.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonequeey9.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonequeey9.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiekod5.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiekod5.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneuy2to6.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneuy2to6.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaghah1.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaghah1.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonereero0.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonereero0.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoe2da5.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoe2da5.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneieb1oo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneieb1oo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneyie6ju.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneyie6ju.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonevi8aer.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonevi8aer.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneohc4so.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneohc4so.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaih5ku.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaih5ku.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepahx9z.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepahx9z.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneow8moh.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneow8moh.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneshoh0d.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneshoh0d.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonejoh2oo.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonejoh2oo.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonepi9ipi.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonepi9ipi.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonego0ies.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonego0ies.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonenexe3w.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonenexe3w.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneboh4ie.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneboh4ie.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoad5ah.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoad5ah.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonezeim2e.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonezeim2e.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneoom2so.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneoom2so.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiem3he.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiem3he.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneee4iet.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneee4iet.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeh1sha.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeh1sha.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonekei7ae.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonekei7ae.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaeph0u.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaeph0u.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneel4eij.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneel4eij.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonethee1l.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonethee1l.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneivae9o.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneivae9o.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaiv9di.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaiv9di.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonetah8ph.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonetah8ph.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonejoong8.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonejoong8.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneiedah5.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneiedah5.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehe2oor.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehe2oor.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneuca6ph.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneuca6ph.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneeuzib9.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneeuzib9.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonehahx2e.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonehahx2e.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzoneaipi6a.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzoneaipi6a.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
subzonewi0ohr.ali-algburi.sb.uclllabs.be.      IN      NS      ns.ali-algburi.sb.uclllabs.be.
subzonewi0ohr.ali-algburi.sb.uclllabs.be.	IN	A	193.191.177.129
