#!/bin/bash
### BEGIN INIT INFO
# Provides:          firewall
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: your description here
### END INIT INFO
if [ "$1" = "start" ];
then
echo "Starting firewall"
iptables-restore < /etc/iptables/rules.v4
ip6tables-restore < /etc/iptables/rules.v6

elif [ "$1" = "stop" ];
then
echo "Stopping firewall"
iptables-restore < /etc/iptables/stopper.v4
ip6tables-restore < /etc/iptables/stopper.v6

elif [ "$1" = "restart" ];
then
echo "Restarting firewall"

iptables-restore < /etc/iptables/stopper.v4
ip6tables-restore < /etc/iptables/stopper.v6

iptables-restore < /etc/iptables/rules.v4
ip6tables-restore < /etc/iptables/rules.v6

else
echo "usage: firewall {start|stop|restart}"
fi

